theme: jekyll-theme-slate
title: Welcome to the Philo’s homepage!
description: Go aheah and bookmark this page. I might make a change or two.
description: And here's a second line of a decription..... go figure.
